### ISSUE TITLE
"Rows per page" text translation

### ISSUE THREAD

**Issue by duykhanhrc** [pablolmedorado/temat#1]
Hi, 

Thanks for the great code.

I got an issue when trying to translate footer table text from Spanish to Vietnamese or English,  but I can not find how to do it. 
Can you please advise

I already tried:

- `frontend\src\plugins\vuetify.js`: Changing locale to `en`
- `frontend\src\components\index\ItemTable.vue`: Adding `itemsPerPageText: "Rows count"` to `footerProps`

But none of them works.

Here is where I am unable to translate

![image](https://user-images.githubusercontent.com/44592718/142755349-03a8ef33-eef4-45a7-b60d-5309631bf313.png)

**Comment by pablolmedorado** [comment]
Hi @duykhanhrc;

Thanks for your kind words. I'm glad the app seems interesting to you.

I've been testing the english language and I have no issues.

This is what I've changed:
```javascript
// frontend/src/plugins/vuetify.js

import Vue from "vue";
import Vuetify from "vuetify/lib";
import es from "vuetify/es5/locale/es";
import en from "vuetify/es5/locale/en";  // <--

Vue.use(Vuetify);

export default new Vuetify({
  lang: {
    locales: { es, en },  // <--
    current: "en",  // <--
  },
...
```
![translated_footer](https://user-images.githubusercontent.com/8086921/142775394-dde6c410-0e4a-4469-a165-3a7cab6e41b3.png)

**Comment by duykhanhrc** [comment]
Thanks,

It was my mistake that I imported the wrong locale character.
